id: azure_compute_vm_guest_configuration_installed_linux
title: Deploy the Linux Guest Configuration extension to enable Guest Configuration assignments on Linux VMs
description: This policy deploys the Linux Guest Configuration extension to Linux virtual machines hosted in Azure that are supported by Guest Configuration. The Linux Guest Configuration extension is a prerequisite for all Linux Guest Configuration assignments and must be deployed to machines before using any Linux Guest Configuration policy definition.
integration_type:
  - azure_subscription
parameters: []
policy:
    language: sql
    primary_resource: azure_compute_virtual_machine
    definition: |
        WITH agent_installed_vm AS (
          SELECT
            DISTINCT a.vm_id
          FROM
            azure_compute_virtual_machine AS a,
            JSONB_ARRAY_ELEMENTS(extensions) AS b
          WHERE
            b ->> 'Publisher' = 'Microsoft.GuestConfiguration'
            AND b ->> 'ProvisioningState' = 'Succeeded'
            AND b ->> 'ExtensionType' = 'ConfigurationforLinux'
            AND b ->> 'Name' LIKE '%AzurePolicyforLinux'
        )
        SELECT
          a.vm_id AS resource,
          a.platform_integration_id AS platform_integration_id,
          a.platform_resource_id AS platform_resource_id,
          CASE
            WHEN a.os_type <> 'Linux' THEN 'skip'
            WHEN b.vm_id IS NOT NULL THEN 'ok'
            ELSE 'alarm'
          END AS status,
          CASE
            WHEN a.os_type <> 'Linux' THEN a.title || ' is of ' || a.os_type || ' operating system.'
            WHEN b.vm_id IS NOT NULL THEN a.title || ' have guest configuration extension installed.'
            ELSE a.title || ' guest configuration extension not installed.'
          END AS reason,
          a.resource_group AS resource_group,
          sub.display_name AS subscription
        FROM
          azure_compute_virtual_machine AS a
          LEFT JOIN agent_installed_vm AS b ON a.vm_id = b.vm_id,
          azure_subscription AS sub
        WHERE
          sub.subscription_id = a.subscription_id
severity: medium
tags:
    nist_sp_800_53_rev_5:
      - 'true'
    service:
      - Azure/Compute
