id: azure_compute_vm_allowlist_rules_in_adaptive_application_control_policy_updated
title: Allowlist rules in your adaptive application control policy should be updated
description: Monitor for changes in behavior on groups of machines configured for auditing by Azure Security Center's adaptive application controls. Security Center uses machine learning to analyze the running processes on your machines and suggest a list of known-safe applications. These are presented as recommended apps to allow in adaptive application control policies.
integration_type:
  - azure_subscription
parameters: []
policy:
    language: sql
    primary_resource: ''
    definition: |
        SELECT
          id AS resource,
          platform_integration_id AS platform_integration_id,
          platform_resource_id AS platform_resource_id,
          'info' AS status,
          'Manual verification required.' AS reason,
          display_name AS subscription
        FROM
          azure_subscription;
severity: low
tags:
    manual-verification:
      - 'true'
