id: azure_compute_vm_guest_configuration_with_user_and_system_assigned_managed_identity
title: Add system-assigned managed identity to enable Guest Configuration assignments on VMs with a user-assigned identity
description: This policy adds a system-assigned managed identity to virtual machines hosted in Azure that are supported by Guest Configuration and have at least one user-assigned identity but do not have a system-assigned managed identity. A system-assigned managed identity is a prerequisite for all Guest Configuration assignments and must be added to machines before using any Guest Configuration policy definitions.
integration_type:
  - azure_subscription
parameters: []
policy:
    language: sql
    primary_resource: azure_compute_virtual_machine
    definition: |
        WITH gc_installed_vm AS (
          SELECT
            DISTINCT a.vm_id,
            title
          FROM
            azure_compute_virtual_machine AS a,
            jsonb_array_elements(extensions) AS b
          WHERE
            b ->> 'Publisher' = 'Microsoft.GuestConfiguration'
        )
        SELECT
          a.vm_id AS resource,
          a.platform_integration_id AS platform_integration_id,
          a.platform_resource_id AS platform_resource_id,
          CASE
            WHEN b.vm_id IS NULL THEN 'skip'
            WHEN NOT string_to_array(a.identity ->> 'type', ', ') @> ARRAY['UserAssigned'] THEN 'skip'
            WHEN string_to_array(a.identity ->> 'type', ', ') @> ARRAY['UserAssigned', 'SystemAssigned'] THEN 'ok'
            ELSE 'alarm'
          END AS status,
          CASE
            WHEN b.vm_id IS NULL THEN a.title || ' guest configuration extension not installed.'
            WHEN NOT string_to_array(a.identity ->> 'type', ', ') @> ARRAY['UserAssigned'] THEN a.title || ' does not have user assigned managed identity.'
            WHEN string_to_array(a.identity ->> 'type', ', ') @> ARRAY['UserAssigned', 'SystemAssigned'] THEN a.title || ' guest configuration extension installed with user and system assigned managed identity.'
            ELSE a.title || ' guest configuration extension not installed with user and system assigned managed identity.'
          END AS reason,
          a.resource_group AS resource_group,
          sub.display_name AS subscription
        FROM
          azure_compute_virtual_machine AS a
        LEFT JOIN
          gc_installed_vm AS b ON a.vm_id = b.vm_id,
          azure_subscription AS sub
        WHERE
          sub.subscription_id = a.subscription_id;
severity: medium
tags:
    nist_sp_800_53_rev_5:
      - 'true'
    pci_dss_v321:
      - 'true'
    service:
      - Azure/Compute
