id: azure_application_gateway_waf_uses_specified_mode
title: Web Application Firewall (WAF) should use the specified mode for Application Gateway
description: Mandates the use of 'Detection' or 'Prevention' mode to be active on all Web Application Firewall policies for Application Gateway.
integration_type:
  - azure_subscription
parameters: []
policy:
    language: sql
    primary_resource: azure_application_gateway
    definition: |
        SELECT
          ag.id AS resource,
          ag.platform_integration_id AS platform_integration_id,
          ag.platform_resource_id AS platform_resource_id,
          CASE
            WHEN (web_application_firewall_configuration::json -> 'PolicySettings' ->> 'mode') IN ('Prevention', 'Detection') THEN 'ok'
            ELSE 'alarm'
          END AS status,
          CASE
            WHEN (web_application_firewall_configuration::json -> 'PolicySettings' ->> 'mode') IN ('Prevention', 'Detection') THEN ag.name || ' WAF mode is set to ' || (web_application_firewall_configuration::json -> 'PolicySettings' ->> 'mode') || '.'
            ELSE ag.name || ' WAF mode is not set to Prevention or Detection mode.'
          END AS reason
        FROM
          azure_application_gateway AS ag
        JOIN
          azure_subscription AS sub 
          ON sub.subscription_id = ag.subscription_id;
severity: low
tags: {}
