id: azure_application_gateway_waf_enabled
title: Web Application Firewall (WAF) should be enabled for Application Gateway
description: Deploy Azure Web Application Firewall (WAF) in front of public facing web applications for additional inspection of incoming traffic. Web Application Firewall (WAF) provides centralized protection of your web applications from common exploits and vulnerabilities such as SQL injections, Cross-Site Scripting, local and remote file executions. You can also restrict access to your web applications by countries, IP address ranges, and other http(s) parameters via custom rules.
integration_type:
  - azure_subscription
parameters: []
policy:
    language: sql
    primary_resource: azure_application_gateway
    definition: |
        SELECT
          ag.id AS resource,
          ag.platform_integration_id AS platform_integration_id,
          ag.platform_resource_id AS platform_resource_id,
          CASE
            WHEN web_application_firewall_configuration IS NOT NULL THEN 'ok'
            ELSE 'alarm'
          END AS status,
          CASE
            WHEN web_application_firewall_configuration IS NOT NULL THEN ag.name || ' WAF enabled.'
            ELSE ag.name || ' WAF disabled.'
          END AS reason,
          ag.resource_group AS resource_group,
          sub.display_name AS subscription
        FROM
          azure_application_gateway AS ag
        JOIN
          azure_subscription AS sub
        ON
          sub.subscription_id = ag.subscription_id;
severity: high
tags:
    nist_sp_800_53_rev_5:
      - 'true'
    service:
      - Azure/Network
