id: azure_app_configuration_sku_standard
title: App Configuration should use standard SKU
description: Ensure that App Configuration uses standard SKU tier. This control is non-compliant if App Configuration does not use standard SKU.
integration_type:
  - azure_subscription
parameters: []
policy:
    language: sql
    primary_resource: azure_app_configuration
    definition: |
        SELECT
          a.id AS resource,
          a.platform_integration_id AS platform_integration_id,
          a.platform_resource_id AS platform_resource_id,
          CASE
            WHEN sku_name = 'standard' THEN 'ok'
            ELSE 'alarm'
          END AS status,
          a.name || ' has ' || sku_name || ' SKU tier.' AS reason
        FROM
          azure_app_configuration AS a,
          azure_subscription AS sub;
severity: low
tags: {}
