id: azure_compute_vm_adaptive_application_controls_enabled
title: Adaptive application controls for defining safe applications should be enabled on your machines
description: Enable application controls to define the list of known-safe applications running on your machines, and alert you when other applications run. This helps harden your machines against malware. To simplify the process of configuring and maintaining your rules, Security Center uses machine learning to analyze the applications running on each machine and suggest the list of known-safe applications.
integration_type:
  - azure_subscription
parameters: []
policy:
    language: sql
    primary_resource: ''
    definition: |
        SELECT
          id AS resource,
          platform_integration_id AS platform_integration_id,
          platform_resource_id AS platform_resource_id,
          'info' AS status,
          'Manual verification required. Check control description for more details.' AS reason,
          display_name AS subscription
        FROM
          azure_subscription;
severity: low
tags:
    manual-verification:
      - 'true'
