id: azure_monitor_application_insights_configured
title: Ensure Application Insights are Configured
description: Application Insights within Azure act as an Application Performance Monitoring solution providing valuable data into how well an application performs and additional information when performing incident response. The types of log data collected include application metrics, telemetry data, and application trace logging data providing organizations with detailed information about application activity and application transactions.
integration_type:
  - azure_subscription
parameters: []
policy:
    language: sql
    primary_resource: azure_subscription
    definition: |
        WITH application_insights AS (
          SELECT
            subscription_id,
            COUNT(*) AS no_application_insight
          FROM
            azure_application_insight
          GROUP BY
            subscription_id
        )
        SELECT
          sub.id AS resource,
          sub.platform_integration_id AS platform_integration_id,
          sub.platform_resource_id AS platform_resource_id,
          CASE
            WHEN i.subscription_id IS NULL THEN 'alarm'
            ELSE 'ok'
          END AS status,
          CASE
            WHEN i.subscription_id IS NULL THEN sub.display_name || ' does not have application insights configured.'
            ELSE sub.display_name || ' has ' || no_application_insight || ' application insights configured.'
          END AS reason,
          sub.display_name AS subscription
        FROM
          azure_subscription AS sub
          LEFT JOIN application_insights AS i ON i.subscription_id = sub.subscription_id;
severity: medium
tags:
    category:
      - Compliance
    cis:
      - 'true'
    cis_item_id:
      - 5.3.1
    cis_level:
      - '2'
    cis_section_id:
      - '5'
    cis_type:
      - automated
    cis_version:
      - v1.4.0
    plugin:
      - azure
    service:
      - Azure/Monitor
