id: azure_securitycenter_additional_email_configured
title: Ensure 'Additional email addresses' is configured with a security contact email
description: Security Center emails the subscription owners whenever a high-severity alert is triggered for their subscription. You should provide a security contact email address as an additional email address.
integration_type:
  - azure_subscription
parameters: []
policy:
    language: sql
    primary_resource: azure_subscription
    definition: |
        WITH contact_info AS (
          SELECT
            jsonb_agg(email) FILTER (WHERE name = 'default' AND email != '') AS default_email,
            COUNT(*) FILTER (WHERE name != 'default') AS non_default_count,
            COUNT(*) FILTER (WHERE name = 'default') AS default_count,
            subscription_id
          FROM
            azure_security_center_contact
          GROUP BY
            subscription_id
          LIMIT 1
        )
        SELECT
          sub.subscription_id AS resource,
          sub.platform_integration_id AS platform_integration_id,
          sub.platform_resource_id AS platform_resource_id,
          CASE
            WHEN non_default_count > 0 THEN 'OK'
            WHEN default_count = 1 AND jsonb_array_length(default_email) != 0 THEN 'OK'
            ELSE 'ALARM'
          END AS status,
          CASE
            WHEN non_default_count > 0 THEN 'Additional email addresses configured.'
            WHEN default_count = 1 AND default_email IS NOT NULL THEN 'Additional email addresses configured.'
            ELSE 'Additional email addresses not configured.'
          END AS reason,
          sub.display_name AS subscription
        FROM
          azure_subscription sub
        LEFT JOIN contact_info ci ON sub.subscription_id = ci.subscription_id;
severity: high
tags:
    category:
      - Compliance
    cis:
      - 'true'
    cis_item_id:
      - '2.13'
    cis_level:
      - '1'
    cis_section_id:
      - '2'
    cis_type:
      - automated
    cis_version:
      - v1.3.0
    plugin:
      - azure
    service:
      - Azure/SecurityCenter
