id: azure_compute_vm_scale_set_security_configuration_vulnerabilities_remediated
title: Vulnerabilities in security configuration on your virtual machine scale sets should be remediated
description: Audit the OS vulnerabilities on your virtual machine scale sets to protect them from attacks.
integration_type:
  - azure_subscription
parameters: []
policy:
    language: sql
    primary_resource: ''
    definition: |
        SELECT
          id AS resource,
          platform_integration_id AS platform_integration_id,
          platform_resource_id AS platform_resource_id,
          'info' AS status,
          'Manual verification required. Check control description for more details.' AS reason,
          display_name AS subscription
        FROM
          azure_subscription;
severity: low
tags:
    manual-verification:
      - 'true'
