id: azure_sql_db_active_directory_admin_configured
title: Ensure that Azure Active Directory Admin is configured
description: Use Azure Active Directory Authentication for authentication with SQL Database.
integration_type:
  - azure_subscription
parameters: []
policy:
    language: sql
    primary_resource: azure_sql_server
    definition: |
        SELECT
          s.id AS resource,
          s.platform_integration_id AS platform_integration_id,
          s.platform_resource_id AS platform_resource_id,
          CASE
            WHEN server_azure_ad_administrator IS NULL THEN 'alarm'
            ELSE 'ok'
          END AS status,
          CASE
            WHEN server_azure_ad_administrator IS NULL THEN name || ' Azure AD authentication not configured.'
            ELSE name || ' Azure AD authentication configured.'
          END AS reason,
          s.resource_group AS resource_group,
          sub.display_name AS subscription
        FROM
          azure_sql_server s,
          azure_subscription sub
        WHERE
          sub.subscription_id = s.subscription_id;
severity: high
tags:
    category:
      - Compliance
    cis:
      - 'true'
    cis_item_id:
      - '4.4'
    cis_level:
      - '1'
    cis_section_id:
      - '4'
    cis_type:
      - automated
    cis_version:
      - v1.3.0
    plugin:
      - azure
    service:
      - Azure/SQL
