id: azure_logic_app_integration_service_environment_encrypted_with_cmk
title: Logic Apps Integration Service Environment should be encrypted with customer-managed keys
description: Deploy into Integration Service Environment to manage encryption at rest of Logic Apps data using customer-managed keys. By default, customer data is encrypted with service-managed keys, but customer-managed keys are commonly required to meet regulatory compliance standards. Customer-managed keys enable the data to be encrypted with an Azure Key Vault key created and owned by you. You have full control and responsibility for the key lifecycle, including rotation and management.
integration_type:
  - azure_subscription
parameters: []
policy:
    language: sql
    primary_resource: ''
    definition: |
        SELECT
          id AS resource,
          platform_integration_id AS platform_integration_id,
          platform_resource_id AS platform_resource_id,
          'info' AS status,
          'Manual verification required.' AS reason,
          display_name AS subscription
        FROM
          azure_subscription;
severity: low
tags:
    manual-verification:
      - 'true'
