id: azure_securitycenter_notify_alerts_configured
title: Email notification for high severity alerts should be enabled
description: To ensure the relevant people in your organization are notified when there is a potential security breach in one of your subscriptions, enable email notifications for high severity alerts in Security Center.
integration_type:
  - azure_subscription
parameters: []
policy:
    language: sql
    primary_resource: azure_subscription
    definition: |
        WITH contact_info AS (
          SELECT
            COUNT(*) FILTER (WHERE alert_notifications = 'On') AS notification_alert_count,
            subscription_id
          FROM
            azure_security_center_contact
          GROUP BY
            subscription_id
          LIMIT 1
        )
        SELECT
          sub.subscription_id AS resource,
          sub.platform_integration_id AS platform_integration_id,
          sub.platform_resource_id AS platform_resource_id,
          CASE
            WHEN notification_alert_count > 0 THEN 'ok'
            ELSE 'alarm'
          END AS status,
          CASE
            WHEN notification_alert_count > 0 THEN '"Notify about alerts with the following severity" set to High.'
            ELSE '"Notify about alerts with the following severity" not set to High.'
          END AS reason,
          sub.display_name AS subscription
        FROM
          azure_subscription sub
        LEFT JOIN contact_info ci ON sub.subscription_id = ci.subscription_id;
severity: low
tags:
    category:
      - Compliance
    cis:
      - 'true'
    cis_item_id:
      - '2.14'
    cis_level:
      - '1'
    cis_section_id:
      - '2'
    cis_type:
      - automated
    cis_version:
      - v1.3.0
    plugin:
      - azure
    service:
      - Azure/SecurityCenter
