ID: aws_glue_security_configuration_3
Title: "List all AWS Glue Security Configurations and Encryption Modes"
Description: "Allows users to query AWS Glue Security Configurations and gain insights into the security configurations of Glue resources."
Connector:
- aws
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      name,
      job_bookmarks_encryption ->> 'JobBookmarksEncryptionMode' as encyption_mode,
      job_bookmarks_encryption ->> 'KmsKeyArn' as kms_key_arn
    from
      aws_glue_security_configuration
    where
      job_bookmarks_encryption ->> 'JobBookmarksEncryptionMode' != 'DISABLED';
  PrimaryTable: null
  ListOfTables: []
  Parameters: []
Tags:
  cloud_asset_management:
  - "true"
  cloud_data_security:
  - "true"
  cloud_provider:
  - aws
  cloud_service:
  - Glue
