ID: aws_ec2_application_load_balancer_metric_request_count_daily_2
Title: "List all daily request count metrics for AWS EC2 Application Load Balancer"
Description: "Allows users to query daily request count metrics of the AWS EC2 Application Load Balancer."
Connector:
- aws
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      name,
      metric_name,
      namespace,
      maximum,
      minimum,
      average
      sample_count,
      timestamp
    from
      aws_ec2_application_load_balancer_metric_request_count_daily
    where
      average < 100
    order by
      name,
      timestamp;
  PrimaryTable: null
  ListOfTables: []
  Parameters: []
Tags:
  cloud_ops:
  - "true"
  cloud_provider:
  - aws
  cloud_service:
  - EC2 Application Load Balancer
