ID: aws_config_retention_configuration_3
Title: "Find AWS Config Retention Configuration Retention Period"
Description: "Allows users to query AWS Config Retention Configuration for information about the retention period that AWS Config uses to retain your configuration items."
Connector:
- aws
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      name,
      retention_period_in_days,
      title,
      region
    from
      aws_config_retention_configuration
    where
      region = 'us-east-1';
  PrimaryTable: null
  ListOfTables: []
  Parameters: []
Tags:
  cloud_ops:
  - "true"
  cloud_provider:
  - aws
  cloud_service:
  - AWS Config
