id: aws_elb_application_lb_redirect_http_request_to_https
title: ELB application load balancers should redirect HTTP requests to HTTPS
description: To help protect data in transit, ensure that your Application Load Balancer automatically redirects unencrypted HTTP requests to HTTPS.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_ec2_application_load_balancer
    definition: |
        WITH detailed_listeners AS (
          SELECT
            arn,
            load_balancer_arn,
            protocol
          FROM
            aws_ec2_load_balancer_listener,
            jsonb_array_elements(default_actions) AS ac
          WHERE
            split_part(arn, '/', 2) = 'app'
            AND protocol = 'HTTP'
            AND ac ->> 'Type' = 'redirect'
            AND ac -> 'RedirectConfig' ->> 'Protocol' = 'HTTPS'
        )
        SELECT
          a.arn AS resource,
          a.platform_integration_id AS platform_integration_id,
          a.platform_resource_id AS platform_resource_id,
          CASE
            WHEN b.load_balancer_arn IS NULL THEN 'alarm'
            ELSE 'ok'
          END AS status,
          CASE
            WHEN b.load_balancer_arn IS NOT NULL THEN a.title || ' associated with HTTP redirection.'
            ELSE a.title || ' not associated with HTTP redirection.'
          END AS reason,
          a.region, 
          a.account_id
        FROM
          aws_ec2_application_load_balancer a
        LEFT JOIN detailed_listeners b 
        ON a.arn = b.load_balancer_arn
severity: high
tags:
    category:
      - Compliance
    cisa_cyber_essentials:
      - 'true'
    fedramp_low_rev_4:
      - 'true'
    fedramp_moderate_rev_4:
      - 'true'
    ffiec:
      - 'true'
    gdpr:
      - 'true'
    gxp_21_cfr_part_11:
      - 'true'
    hipaa_final_omnibus_security_rule_2013:
      - 'true'
    hipaa_security_rule_2003:
      - 'true'
    nist_800_53_rev_4:
      - 'true'
    nist_800_53_rev_5:
      - 'true'
    nist_800_171_rev_2:
      - 'true'
    nist_csf:
      - 'true'
    pci_dss_v321:
      - 'true'
    plugin:
      - aws
    rbi_cyber_security:
      - 'true'
    service:
      - AWS/ELB
    soc_2:
      - 'true'
