id: aws_lambda_function_concurrent_execution_limit_configured
title: Lambda functions concurrent execution limit configured
description: Checks whether the AWS Lambda function is configured with function-level concurrent execution limit. The control is non-compliant if the Lambda function is not configured with function-level concurrent execution limit.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_lambda_function
    definition: |
        SELECT
          arn AS resource,
          platform_integration_id AS platform_integration_id,
          platform_resource_id AS platform_resource_id,
          CASE
            WHEN reserved_concurrent_executions IS NULL THEN 'alarm'
            ELSE 'ok'
          END AS status,
          CASE
            WHEN reserved_concurrent_executions IS NULL THEN title || ' function-level concurrent execution limit not configured.'
            ELSE title || ' function-level concurrent execution limit configured.'
          END AS reason,
          region,
          account_id
        FROM
          aws_lambda_function;
severity: medium
tags:
    category:
      - Compliance
    fedramp_low_rev_4:
      - 'true'
    fedramp_moderate_rev_4:
      - 'true'
    ffiec:
      - 'true'
    hipaa_final_omnibus_security_rule_2013:
      - 'true'
    nist_800_53_rev_5:
      - 'true'
    nist_800_171_rev_2:
      - 'true'
    nist_csf:
      - 'true'
    plugin:
      - aws
    service:
      - AWS/Lambda
    soc_2:
      - 'true'
