id: aws_lambda_function_cors_configuration
title: Lambda functions CORS configuration should not allow all origins
description: Enable this rule to ensure that the CORS configuration for your Lambda functions does not allow all origins.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_lambda_function
    definition: |
        SELECT
          arn AS resource,
          platform_integration_id AS platform_integration_id,
          platform_resource_id AS platform_resource_id,
          CASE
            WHEN url_config IS NULL THEN 'info'
            WHEN url_config -> 'Cors' ->> 'AllowOrigins' = '[\"*\"]' THEN 'alarm'
            ELSE 'ok'
          END AS status,
          CASE
            WHEN url_config IS NULL THEN title || ' does not have a URL config.'
            WHEN url_config -> 'Cors' ->> 'AllowOrigins' = '[\"*\"]' THEN title || ' CORS configuration allows all origins.'
            ELSE title || ' CORS configuration does not allow all origins.'
          END AS reason
        FROM
          aws_lambda_function;
severity: low
tags: {}
