id: aws_vpc_security_group_restrict_ingress_kibana_port
title: VPC security groups should restrict ingress kibana port access from 0.0.0.0/0
description: AWS VPC security groups can help in managing network access by providing stateful filtering of ingress and egress network traffic to AWS resources.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_vpc_security_group
    definition: |
        WITH ingress_kibana_port AS (
          SELECT
            group_id,
            COUNT(*) AS num_ssh_rules
          FROM
            aws_vpc_security_group_rule
          WHERE
            type = 'ingress'
            AND (
              cidr_ipv4 = '0.0.0.0/0'
              OR cidr_ipv6 = '::/0'
            )
            AND (
              (ip_protocol = '-1' AND from_port IS NULL)
              OR (from_port >= 9200 AND to_port <= 9200)
              OR (from_port >= 5601 AND to_port <= 5601)
            )
          GROUP BY
            group_id
        )
        SELECT
          arn AS resource,
          sg.platform_integration_id AS platform_integration_id,
          sg.platform_resource_id AS platform_resource_id,
          CASE
            WHEN k.group_id IS NULL THEN 'ok'
            ELSE 'alarm'
          END AS status,
          CASE
            WHEN k.group_id IS NULL THEN sg.group_id || ' ingress restricted for kibana port from 0.0.0.0/0.'
            ELSE sg.group_id || ' contains ' || k.num_ssh_rules || ' ingress rule(s) allowing kibana port from 0.0.0.0/0.'
          END AS reason
        FROM
          aws_vpc_security_group AS sg
        LEFT JOIN ingress_kibana_port AS k 
          ON k.group_id = sg.group_id;
severity: low
tags: {}
