id: aws_lambda_function_multiple_az_configured
title: Lambda functions should operate in more than one availability zone
description: This control checks if Lambda has more than one availability zone associated. The rule fails if only one availability zone is associated with Lambda.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_lambda_function
    definition: |
        SELECT
          arn AS resource,
          platform_integration_id AS platform_integration_id,
          platform_resource_id AS platform_resource_id,
          CASE
            WHEN vpc_id IS NULL OR vpc_id = '' THEN 'skip'
            ELSE CASE
              WHEN (
                SELECT
                  COUNT(DISTINCT availability_zone_id)
                FROM
                  aws_vpc_subnet
                WHERE
                  subnet_id IN (SELECT jsonb_array_elements_text(vpc_subnet_ids))
              ) >= 2
              THEN 'ok'
              ELSE 'alarm'
            END
          END AS status,
          CASE
            WHEN vpc_id IS NULL OR vpc_id = '' THEN title || ' is not in VPC.'
            ELSE title || ' has ' || jsonb_array_length(vpc_subnet_ids) || ' availability zone(s).'
          END AS reason,
          region,
          account_id
        FROM
          aws_lambda_function;
severity: medium
tags:
    aws_foundational_security:
      - 'true'
    category:
      - Compliance
    foundational_security_category:
      - high_availability
    foundational_security_item_id:
      - lambda_5
    plugin:
      - aws
    service:
      - AWS/Lambda
