ID: aws_config_configuration_recorder_no_failed_deliver_logs
Title: "Config configuration recorder should not fail to deliver logs"
Description: "This control checks whether Config configuration recorder fails to deliver logs. This control is non-compliant if Config configuration recorder fails to deliver logs."
Connector:
- aws
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      arn as resource,
      kaytu_account_id as kaytu_account_id,
      kaytu_resource_id as kaytu_resource_id,
      case
        when status ->> 'LastStatus' = 'FAILURE' then 'alarm'
        else 'ok'
      end as status,
      case
        when status ->> 'LastStatus' = 'FAILURE' then title || ' has failed deliver logs.'
        else title || ' does not have failed deliver logs.'
      end as reason
      
    from
      aws_config_configuration_recorder;
  PrimaryTable: aws_config_configuration_recorder
  ListOfTables:
  - aws_config_configuration_recorder
  Parameters: []
Severity: low
Tags: {}
