id: aws_vpc_configured_to_use_vpc_endpoints
title: VPC should be configured to use VPC endpoints
description: Checks if Service Endpoint for the service provided in rule parameter is created for each AWS Virtual Private Cloud (AWS VPC). The rule is non-compliant if an AWS VPC doesn't have an AWS VPC endpoint created for the service.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_vpc
    definition: |
        SELECT
          arn AS resource,
          platform_integration_id AS platform_integration_id,
          platform_resource_id AS platform_resource_id,
          CASE
            WHEN vpc_id NOT IN (
              SELECT
                vpc_id
              FROM
                aws_vpc_endpoint
              WHERE
                service_name LIKE 'com.amazonaws.' || region || '.ec2'
            ) THEN 'alarm'
            ELSE 'ok'
          END AS status,
          CASE
            WHEN vpc_id NOT IN (
              SELECT
                vpc_id
              FROM
                aws_vpc_endpoint
              WHERE
                service_name LIKE 'com.amazonaws.' || region || '.ec2'
            ) THEN title || ' not configured to use VPC endpoints.'
            ELSE title || ' configured to use VPC endpoints.'
          END AS reason,
          region,
          account_id
        FROM
          aws_vpc;
severity: medium
tags:
    aws_foundational_security:
      - 'true'
    category:
      - Compliance
    foundational_security_category:
      - api_private_access
    foundational_security_item_id:
      - ec2_10
    plugin:
      - aws
    service:
      - AWS/EC2
