id: aws_mandatory_sql_elastic_beanstalk_environment_mandatory
title: Elastic beanstalk environments should have mandatory tags
description: Check if Elastic beanstalk environments have mandatory tags.
integration_type:
  - aws_cloud_account
parameters:
  - key: awsMandatoryTags
policy:
    language: sql
    primary_resource: aws_elastic_beanstalk_environment
    definition: |
        WITH analysis AS (
          SELECT
            platform_integration_id,
            platform_resource_id,
            arn,
            title,
            tags ?& '{{.awsMandatoryTags}}'::text[] AS has_mandatory_tags,
            to_jsonb('{{.awsMandatoryTags}}'::text[]) - ARRAY(SELECT jsonb_object_keys(tags)) AS missing_tags,
            region,
            account_id,
            tags,
            _ctx
          FROM
            aws_elastic_beanstalk_environment
        )
        SELECT
          platform_integration_id,
          platform_resource_id,
          arn AS resource,
          CASE
            WHEN has_mandatory_tags THEN 'ok'
            ELSE 'alarm'
          END AS status,
          CASE
            WHEN has_mandatory_tags THEN title || ' has all mandatory tags.'
            ELSE title || ' is missing tags: ' || array_to_string(ARRAY(SELECT jsonb_array_elements_text(missing_tags)), ', ') || '.'
          END AS reason,
          region,
          account_id
        FROM
          analysis;
severity: high
tags: {}
