id: aws_api_gatewayv2_route_authorizer_configured
title: API Gateway V2 authorizer should be configured
description: This control checks whether API Gateway V2 has an authorizer configured. This rule is non-compliant if API Gateway V2 has no authorizers configured.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_api_gatewayv2_route
    definition: |
        SELECT
          'arn:' || partition || ':apigateway:' || region || '::/apis/' || api_id || '/routes/' || route_id AS resource,
          platform_integration_id AS platform_integration_id,
          platform_resource_id AS platform_resource_id,
          CASE
            WHEN authorizer_id IS NULL THEN 'alarm'
            ELSE 'ok'
          END AS status,
          CASE
            WHEN authorizer_id IS NULL THEN route_id || ' authorizer not configured.'
            ELSE route_id || ' authorizer ' || authorizer_id || ' configured.'
          END AS reason
        FROM
          aws_api_gatewayv2_route;
severity: low
tags: {}
