id: aws_autoscaling_group_multiple_az_configured
title: EC2 auto scaling groups should cover multiple availability zones
description: This control checks whether an AWS EC2 Auto Scaling group spans multiple availability zones. The control fails if an auto scaling group does not span multiple availability zones.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_ec2_autoscaling_group
    definition: |
        SELECT
          autoscaling_group_arn AS resource,
          platform_integration_id AS platform_integration_id,
          platform_resource_id AS platform_resource_id,
          CASE
            WHEN jsonb_array_length(availability_zones) > 1 THEN 'ok'
            ELSE 'alarm'
          END AS status,
          title || ' has ' || jsonb_array_length(availability_zones) || ' availability zone(s).' AS reason,
          region,
          account_id
        FROM
          aws_ec2_autoscaling_group;
severity: medium
tags:
    aws_foundational_security:
      - 'true'
    category:
      - Compliance
    foundational_security_category:
      - high_availability
    foundational_security_item_id:
      - autoscaling_2
    plugin:
      - aws
    service:
      - AWS/AutoScaling
