id: aws_sagemaker_endpoint_configuration_encryption_at_rest_enabled
title: SageMaker endpoint configuration encryption should be enabled
description: To help protect data at rest, ensure encryption with AWS Key Management Service (AWS KMS) is enabled for your SageMaker endpoint.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_sagemaker_endpoint_configuration
    definition: |
        SELECT
          arn AS resource,
          platform_integration_id AS platform_integration_id,
          platform_resource_id AS platform_resource_id,
          CASE
            WHEN kms_key_id IS NULL THEN 'alarm'
            ELSE 'ok'
          END AS status,
          CASE
            WHEN kms_key_id IS NULL THEN title || ' encryption at rest disabled.'
            ELSE title || ' encryption at rest enabled.'
          END AS reason,
          region,
          account_id
        FROM
          aws_sagemaker_endpoint_configuration;
severity: high
tags:
    category:
      - Compliance
    cisa_cyber_essentials:
      - 'true'
    fedramp_low_rev_4:
      - 'true'
    fedramp_moderate_rev_4:
      - 'true'
    gdpr:
      - 'true'
    gxp_21_cfr_part_11:
      - 'true'
    gxp_eu_annex_11:
      - 'true'
    hipaa_final_omnibus_security_rule_2013:
      - 'true'
    hipaa_security_rule_2003:
      - 'true'
    nist_800_53_rev_4:
      - 'true'
    nist_800_53_rev_5:
      - 'true'
    nist_800_171_rev_2:
      - 'true'
    nist_csf:
      - 'true'
    pci_dss_v321:
      - 'true'
    plugin:
      - aws
    rbi_cyber_security:
      - 'true'
    service:
      - AWS/SageMaker
    soc_2:
      - 'true'
