id: aws_elb_application_lb_with_outbound_rule
title: ELB application load balancers should have at least one outbound rule
description: Ensure application load balancers have at least one outbound rule in all the attached security groups. A security group without any outbound rule rejects all outgoing traffic. This means that all outgoing traffic originating from your cloud assets (instances, containers, etc.) will be dropped when it reaches the ELB layer.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_ec2_application_load_balancer
    definition: |
        WITH sg_with_outbound AS (
          SELECT
            arn,
            sg
          FROM
            aws_ec2_application_load_balancer,
            jsonb_array_elements_text(security_groups) AS sg
            LEFT JOIN aws_vpc_security_group_rule AS sgr ON sg = sgr.group_id
          WHERE
            sgr.type = 'egress'
          GROUP BY
            sg, arn
        ),
        application_lb_without_outbound AS (
          SELECT
            DISTINCT arn
          FROM
            aws_ec2_application_load_balancer,
            jsonb_array_elements_text(security_groups) AS s
          WHERE
            s NOT IN (SELECT sg FROM sg_with_outbound)
        )
        SELECT
          DISTINCT a.arn AS resource,
          a.platform_integration_id AS platform_integration_id,
          a.platform_resource_id AS platform_resource_id,
          CASE
            WHEN a.security_groups IS NULL THEN 'alarm'
            WHEN o.arn IS NOT NULL THEN 'alarm'
            ELSE 'ok'
          END AS status,
          CASE
            WHEN a.security_groups IS NULL THEN a.title || ' does not have security group attached.'
            WHEN o.arn IS NOT NULL THEN a.title || ' all attached security groups do not have outbound rule(s).'
            ELSE a.title || ' all attached security groups have outbound rule(s).'
          END AS reason
        FROM
          aws_ec2_application_load_balancer AS a
          LEFT JOIN application_lb_without_outbound AS o ON a.arn = o.arn;
severity: low
tags: {}
