id: aws_autoscaling_launch_config_hop_limit
title: EC2 auto scaling group launch configurations should not have metadata response hop limit greater than 1
description: This control checks the number of network hops that a metadata token can travel. The control fails if the metadata response hop limit is greater than 1.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_ec2_launch_configuration
    definition: |
        SELECT
          launch_configuration_arn AS resource,
          platform_integration_id AS platform_integration_id,
          platform_resource_id AS platform_resource_id,
          CASE
            WHEN metadata_options_put_response_hop_limit IS NULL THEN 'ok'
            WHEN metadata_options_put_response_hop_limit > 1 THEN 'alarm'
            ELSE 'ok'
          END AS status,
          CASE
            WHEN metadata_options_put_response_hop_limit IS NULL THEN title || ' metadata response hop limit set to default.'
            ELSE title || ' has a metadata response hop limit of ' || metadata_options_put_response_hop_limit || '.'
          END AS reason,
          region,
          account_id
        FROM
          aws_ec2_launch_configuration;
severity: high
tags:
    aws_foundational_security:
      - 'true'
    category:
      - Compliance
    foundational_security_category:
      - secure_network_configuration
    foundational_security_item_id:
      - autoscaling_4
    plugin:
      - aws
    service:
      - AWS/AutoScaling
