id: aws_elb_application_lb_waf_enabled
title: ELB application load balancers should have Web Application Firewall (WAF) enabled
description: Ensure AWS WAF is enabled on Elastic Load Balancers (ELB) to help protect web applications.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_ec2_application_load_balancer
    definition: |
        SELECT
          arn AS resource,
          platform_integration_id AS platform_integration_id,
          platform_resource_id AS platform_resource_id,
          CASE
            WHEN load_balancer_attributes @> '[{"Key":"waf.fail_open.enabled","Value":"true"}]' THEN 'ok'
            ELSE 'alarm'
          END AS status,
          CASE
            WHEN load_balancer_attributes @> '[{"Key":"waf.fail_open.enabled","Value":"true"}]' THEN title || ' WAF enabled.'
            ELSE title || ' WAF disabled.'
          END AS reason,
          region,
          account_id
        FROM
          aws_ec2_application_load_balancer;
severity: high
tags:
    category:
      - Compliance
    cisa_cyber_essentials:
      - 'true'
    fedramp_low_rev_4:
      - 'true'
    fedramp_moderate_rev_4:
      - 'true'
    ffiec:
      - 'true'
    nist_800_53_rev_4:
      - 'true'
    nist_800_53_rev_5:
      - 'true'
    nist_800_171_rev_2:
      - 'true'
    nist_csf:
      - 'true'
    pci_dss_v321:
      - 'true'
    plugin:
      - aws
    rbi_cyber_security:
      - 'true'
    service:
      - AWS/ELB
    soc_2:
      - 'true'
