id: aws_ecs_task_definition_container_environment_no_secret
title: ECS task definition containers should not have secrets passed as environment variables
description: This control checks if the key value of any variables in the environment parameter of container definitions includes AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, or ECS_ENGINE_AUTH_DATA. This control fails if a single environment variable in any container definition equals AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, or ECS_ENGINE_AUTH_DATA. This control does not cover environmental variables passed in from other locations such as AWS S3.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_ecs_task_definition
    definition: |
        WITH definitions_with_secret_environment_variable AS (
          SELECT DISTINCT
            task_definition_arn AS arn
          FROM
            aws_ecs_task_definition,
            jsonb_array_elements(container_definitions) AS c,
            jsonb_array_elements(
              CASE jsonb_typeof(c -> 'Environment')
                WHEN 'array' THEN (c -> 'Environment')
                ELSE NULL
              END
            ) AS s
          WHERE
            s ->> 'Name' LIKE ANY (ARRAY ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'ECS_ENGINE_AUTH_DATA'])

          UNION

          SELECT DISTINCT
            task_definition_arn AS arn
          FROM
            aws_ecs_task_definition,
            jsonb_array_elements(container_definitions) AS c,
            jsonb_array_elements(
              CASE jsonb_typeof(c -> 'Secrets')
                WHEN 'array' THEN (c -> 'Secrets')
                ELSE NULL
              END
            ) AS s
          WHERE
            s ->> 'Name' LIKE ANY (ARRAY ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'ECS_ENGINE_AUTH_DATA'])
        )

        SELECT
          d.task_definition_arn AS resource,
          d.platform_integration_id AS platform_integration_id,
          d.platform_resource_id AS platform_resource_id,
          CASE
            WHEN e.arn IS NULL THEN 'ok'
            ELSE 'alarm'
          END AS status,
          CASE
            WHEN e.arn IS NULL THEN d.title || ' container environment variables does not have secrets.'
            ELSE d.title || ' container environment variables have secrets.'
          END AS reason,
          region,
          account_id
        FROM
          aws_ecs_task_definition AS d
        LEFT JOIN definitions_with_secret_environment_variable AS e
          ON d.task_definition_arn = e.arn;
severity: high
tags:
    aws_foundational_security:
      - 'true'
    category:
      - Compliance
    foundational_security_category:
      - credentials_not_hard_coded
    foundational_security_item_id:
      - ecs_8
    plugin:
      - aws
    service:
      - AWS/ECS
