id: aws_elb_application_classic_lb_logging_enabled
title: ELB application and classic load balancer logging should be enabled
description: Elastic Load Balancing activity is a central point of communication within an environment.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: ''
    definition: |
        (
          SELECT
            arn AS resource,
            platform_integration_id AS platform_integration_id,
            platform_resource_id AS platform_resource_id,
            'aws_ec2_application_load_balancer' AS platform_table_name,
            CASE
              WHEN load_balancer_attributes @> '[{"Key": "access_logs.s3.enabled", "Value": "true"}]' THEN 'ok'
              ELSE 'alarm'
            END AS status,
            CASE
              WHEN load_balancer_attributes @> '[{"Key": "access_logs.s3.enabled", "Value": "true"}]' THEN title || ' logging enabled.'
              ELSE title || ' logging disabled.'
            END AS reason,
            region,
            account_id
          FROM aws_ec2_application_load_balancer
        )
        UNION
        (
          SELECT
            'arn:' || partition || ':elasticloadbalancing:' || region || ':' || account_id || ':loadbalancer/' || title AS resource,
            platform_integration_id AS platform_integration_id,
            platform_resource_id AS platform_resource_id,
            'aws_ec2_classic_load_balancer' AS platform_table_name,
            CASE
              WHEN access_log_enabled = 'true' THEN 'ok'
              ELSE 'alarm'
            END AS status,
            CASE
              WHEN access_log_enabled = 'true' THEN title || ' logging enabled.'
              ELSE title || ' logging disabled.'
            END AS reason,
            region,
            account_id
          FROM aws_ec2_classic_load_balancer
        );
severity: high
tags:
    category:
      - Compliance
    cis_controls_v8_ig1:
      - 'true'
    cisa_cyber_essentials:
      - 'true'
    fedramp_low_rev_4:
      - 'true'
    fedramp_moderate_rev_4:
      - 'true'
    ffiec:
      - 'true'
    gdpr:
      - 'true'
    gxp_21_cfr_part_11:
      - 'true'
    hipaa_final_omnibus_security_rule_2013:
      - 'true'
    hipaa_security_rule_2003:
      - 'true'
    nist_800_53_rev_4:
      - 'true'
    nist_800_53_rev_5:
      - 'true'
    nist_800_171_rev_2:
      - 'true'
    nist_csf:
      - 'true'
    pci_dss_v321:
      - 'true'
    plugin:
      - aws
    rbi_cyber_security:
      - 'true'
    service:
      - AWS/ELB
    soc_2:
      - 'true'
