id: aws_configure_aws_backup_vault_access_policy
title: Configure AWS Backup Vault Access Policy
description: Prevent deletion of backups using an Amazon Backup vault resource-based access policy.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_backup_vault
    definition: |
        SELECT
          name AS resource,
          platform_resource_id,
          platform_integration_id,
          CASE
            WHEN policy IS NULL THEN 'alarm'
            WHEN EXISTS (
              SELECT 1
              FROM jsonb_array_elements(policy -> 'Statement') AS s
              WHERE 
                (s ->> 'Effect') = 'Deny' 
                AND 
                (s ->> 'Action') LIKE '%backup:DeleteRecoveryPoint%'
            ) THEN 'ok'
            ELSE 'alarm'
          END AS status,
          CASE
            WHEN policy IS NULL THEN 'there is no policy defined'
            WHEN EXISTS (
              SELECT 1
              FROM jsonb_array_elements(policy -> 'Statement') AS s
              WHERE 
                (s ->> 'Effect') = 'Deny'
                AND 
                (s ->> 'Action') LIKE '%backup:DeleteRecoveryPoint%'
            ) THEN 'has deletion protection enabled for its backups.'
            ELSE 'does not have deletion protection enabled for its backups.'
          END AS reason,
          region,
          account_id
        FROM
          aws_backup_vault
severity: high
tags:
    platform_score_cloud_service_name:
      - AWS Backup
    platform_score_use_case:
      - Exposed Endpoints
    score_service_name:
      - AWS Backup
    score_tags:
      - Exposed Endpoints
