ID: aws_elastic_beanstalk_environment_5
Title: "List All AWS Elastic Beanstalk Environment Configurations and Status"
Description: "Allows users to query AWS Elastic Beanstalk Environments to gain insights into their configuration, status, health, related applications, and other metadata."
Connector:
- aws
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      environment_name,
      a ->> 'ActionDescription' as action_description,
      a ->> 'ActionId' as action_id,
      a ->> 'ActionType' as action_type,
      a ->> 'Status' as action_status,
      a ->> 'WindowStartTime' as action_window_start_time
    from
      aws_elastic_beanstalk_environment,
      jsonb_array_elements(managed_actions) as a;
  PrimaryTable: null
  ListOfTables: []
  Parameters: []
Tags:
  cloud_ops:
  - "true"
  cloud_provider:
  - aws
  cloud_service:
  - Elastic Beanstalk
