ID: aws_kinesisanalyticsv2_application_2
Title: "Find AWS Kinesis Analytics Applications and Details"
Description: "Allows users to query AWS Kinesis Analytics Applications to retrieve detailed information about each application, including the name, ARN, description, status, runtime environment, and more."
Connector:
- aws
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      application_name,
      application_version_id,
      application_arn,
      application_status
    from
      aws_kinesisanalyticsv2_application
    where
      application_version_id > 1;
  PrimaryTable: null
  ListOfTables: []
  Parameters: []
Tags:
  cloud_asset_management:
  - "true"
  cloud_ops:
  - "true"
  cloud_provider:
  - aws
  cloud_service:
  - Kinesis Analytics
