ID: aws_glue_security_configuration_1
Title: "Find AWS Glue Security Configurations and Insights"
Description: "Allows users to query AWS Glue Security Configurations and gain insights into the security configurations of Glue resources."
Connector:
- aws
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      name,
      created_time_stamp,
      cloud_watch_encryption,
      job_bookmarks_encryption,
      s3_encryption
    from
      aws_glue_security_configuration;
  PrimaryTable: null
  ListOfTables: []
  Parameters: []
Tags:
  cloud_asset_management:
  - "true"
  cloud_data_security:
  - "true"
  cloud_ops:
  - "true"
  cloud_provider:
  - aws
  cloud_service:
  - Glue
