ID: aws_eks_identity_provider_config_2
Title: "Find all Amazon EKS Identity Provider Configurations"
Description: "Allows users to query Amazon EKS Identity Provider Configurations for detailed information about the identity provider configurations for Amazon EKS clusters."
Connector:
- aws
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      name,
      arn,
      cluster_name,
      type
    from
      aws_eks_identity_provider_config
    where 
      type = 'oidc';
  PrimaryTable: null
  ListOfTables: []
  Parameters: []
Tags:
  cloud_identity_security:
  - "true"
  cloud_provider:
  - aws
  cloud_service:
  - Amazon EKS
