id: azure_disable_plain_ftp_deployment
title: Disable Plain FTP Deployment
description: Ensure that FTP access is disabled for your Azure App Services web applications.
integration_type:
  - azure_subscription
parameters: []
policy:
    language: sql
    primary_resource: azure_app_service_web_app
    definition: |
        SELECT
          wa.name AS resource,
          wa.platform_resource_id,
          wa.platform_integration_id,
          CASE
            WHEN configuration -> 'properties' ->> 'ftpsState' = 'AllAllowed' THEN 'alarm'
            ELSE 'ok'
          END AS status,
          CASE
            WHEN configuration -> 'properties' ->> 'ftpsState' = 'AllAllowed' THEN name || ' default FTP deployment is not disabled'
            ELSE name || ' default FTP deployment is disabled'
          END AS reason,
          wa.resource_group AS resource_group,
          sub.display_name AS subscription
        FROM
          azure_app_service_web_app AS wa
          LEFT JOIN azure_subscription AS sub ON wa.subscription_id = sub.subscription_id
severity: medium
tags:
    platform_score_cloud_service_name:
      - Azure App Services
    platform_score_use_case:
      - Lacking High Availability
    score_service_name:
      - Azure App Services
    score_tags:
      - Lacking High Availability
