ID: aws_emr_cluster_security_configuration_enabled
Title: "EMR clusters should have security configuration enabled"
Description: "Ensure EMR cluster have security configuration enabled. This control fails if security configuration is not enabled for EMR cluster."
Connector:
- aws
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      cluster_arn as resource,
      kaytu_account_id as kaytu_account_id,
      kaytu_resource_id as kaytu_resource_id,
      case
        when security_configuration is not null then 'ok'
        else 'alarm'
      end as status,
      case
        when security_configuration is not null then title || ' security configuration enabled.'
        else title || ' security configuration disabled.'
      end as reason
      
      
    from
      aws_emr_cluster;
  PrimaryTable: aws_emr_cluster
  ListOfTables:
  - aws_emr_cluster
  Parameters: []
Severity: low
Tags: {}
