id: aws_elbv2_alb_listener_security
title: ELBv2 ALB Listener Security
description: Ensure ELBv2 ALBs are using a secure protocol.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_ec2_application_load_balancer
    definition: |
        SELECT
          al.arn AS resource,
          al.platform_resource_id,
          al.platform_integration_id,
          CASE
            WHEN STRING_AGG(ll.protocol, ',') ILIKE '%HTTPS%' THEN 'ok'
            ELSE 'alarm'
          END AS status,
          CASE
            WHEN STRING_AGG(ll.protocol, ',') ILIKE '%HTTPS%' THEN 'alb is using a secure protocol'
            ELSE 'alb is not using a secure protocol'
          END AS reason,
          al.region,
          al.account_id
        FROM
          aws_ec2_application_load_balancer al
        LEFT JOIN
          aws_ec2_load_balancer_listener ll
        ON
          al.arn = ll.load_balancer_arn
        GROUP BY
          al.arn,
          al.platform_resource_id,
          al.platform_integration_id,
          al.title,
          al.region,
          al.account_id;
severity: high
tags:
    platform_score_cloud_service_name:
      - AWS Elastic Load Balancing V2 (ELBv2)
    platform_score_use_case:
      - Unencrypted Traffic
    score_service_name:
      - AWS Elastic Load Balancing V2 (ELBv2)
    score_tags:
      - Unencrypted Traffic
