id: aws_configure_multiple_availability_zones_for_load_balancers
title: Configure Multiple Availability Zones for Load Balancers
description: Ensure that Amazon Gateway Load Balancers are using Multi-AZ configurations.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: ''
    definition: |
        SELECT
          arn AS resource,
          platform_resource_id,
          platform_integration_id,
          CASE
            WHEN jsonb_array_length(availability_zones) < 2 THEN 'alarm'
            ELSE 'ok'
          END AS status,
          title || ' has ' || jsonb_array_length(availability_zones) || ' availability zone(s).' AS reason,
          region,
          account_id
        FROM
          aws_ec2_application_load_balancer
        UNION
        SELECT
          arn AS resource,
          platform_resource_id,
          platform_integration_id,
          CASE
            WHEN jsonb_array_length(availability_zones) < 2 THEN 'alarm'
            ELSE 'ok'
          END AS status,
          title || ' has ' || jsonb_array_length(availability_zones) || ' availability zone(s).' AS reason,
          region,
          account_id
        FROM
          aws_ec2_network_load_balancer
        UNION
        SELECT
          arn AS resource,
          platform_resource_id,
          platform_integration_id,
          CASE
            WHEN jsonb_array_length(availability_zones) < 2 THEN 'alarm'
            ELSE 'ok'
          END AS status,
          title || ' has ' || jsonb_array_length(availability_zones) || ' availability zone(s).' AS reason,
          region,
          account_id
        FROM
          aws_ec2_gateway_load_balancer;
severity: high
tags:
    platform_score_cloud_service_name:
      - AWS Elastic Load Balancing V2 (ELBv2)
    platform_score_use_case:
      - Lacking High Availability
    score_service_name:
      - AWS Elastic Load Balancing V2 (ELBv2)
    score_tags:
      - Lacking High Availability
