id: aws_unused_application_load_balancers
title: Unused Application Load Balancers
description: Identify unused Applications Load Balancers, and delete them to help lower the cost of your monthly AWS bill.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_ec2_application_load_balancer
    definition: |
        WITH target_resource AS (
          SELECT
            load_balancer_arn,
            target_health_descriptions,
            target_type
          FROM
            aws_ec2_target_group,
            jsonb_array_elements_text(load_balancer_arns) AS load_balancer_arn
        )
        SELECT
          a.arn AS resource,
          platform_resource_id,
          platform_integration_id,
          CASE
            WHEN b.load_balancer_arn IS NULL THEN 'alarm'
            ELSE 'ok'
          END AS status,
          CASE
            WHEN b.load_balancer_arn IS NULL THEN a.title || ' has no target registered.'
            ELSE a.title || ' has registered target of type ' || b.target_type || '.'
          END AS reason,
          a.region,
          a.account_id
        FROM
          aws_ec2_application_load_balancer a
        LEFT JOIN target_resource b ON a.arn = b.load_balancer_arn;
severity: high
tags:
    platform_score_cloud_service_name:
      - AWS Elastic Load Balancing V2 (ELBv2)
    platform_score_use_case:
      - Orphaned Resources
    score_service_name:
      - AWS Elastic Load Balancing V2 (ELBv2)
    score_tags:
      - Orphaned Resources
