id: aws_elbv2_nlb_listener_security
title: ELBv2 NLB Listener Security
description: Ensure that your AWS Network Load Balancer listeners are using a secure protocol such as TLS.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_ec2_network_load_balancer
    definition: |
        WITH tls_listeners AS (
          SELECT
            DISTINCT load_balancer_arn
          FROM
            aws_ec2_load_balancer_listener
          WHERE
            protocol = 'TLS'
            AND ssl_policy NOT IN (
              'ELBSecurityPolicy-2016-08',
              'ELBSecurityPolicy-FS-2018-0',
              'ELBSecurityPolicy-TLS13-1-2-Ext1-2021-06',
              'ELBSecurityPolicy-TLS13-1-2-2021-06'
            )
          GROUP BY
            load_balancer_arn
        ),
        nwl_without_tls_listener AS (
          SELECT
            load_balancer_arn,
            COUNT(*)
          FROM
            aws_ec2_load_balancer_listener
          WHERE
            protocol = 'TLS'
          GROUP BY
            load_balancer_arn
        )
        SELECT
          lb.arn AS resource,
          platform_resource_id,
          platform_integration_id,
          CASE
            WHEN l.load_balancer_arn IS NOT NULL
            AND lb.arn IN (
              SELECT
                load_balancer_arn
              FROM
                tls_listeners
            ) THEN 'alarm'
            WHEN l.load_balancer_arn IS NOT NULL THEN 'ok'
            ELSE 'info'
          END AS status,
          CASE
            WHEN l.load_balancer_arn IS NOT NULL
            AND lb.arn IN (
              SELECT
                load_balancer_arn
              FROM
                tls_listeners
            ) THEN lb.title || ' TLS listener security policy not updated.'
            WHEN l.load_balancer_arn IS NOT NULL THEN lb.title || ' TLS listener security policy updated.'
            ELSE lb.title || ' does not use TLS listener.'
          END AS reason,
          lb.region,
          lb.account_id
        FROM
          aws_ec2_network_load_balancer AS lb
          LEFT JOIN nwl_without_tls_listener AS l ON l.load_balancer_arn = lb.arn;
severity: high
tags:
    platform_score_cloud_service_name:
      - AWS Elastic Load Balancing V2 (ELBv2)
    platform_score_use_case:
      - Unencrypted Traffic
    score_service_name:
      - AWS Elastic Load Balancing V2 (ELBv2)
    score_tags:
      - Unencrypted Traffic
