ID: azure_compute_vm_guest_configuration_with_user_and_system_assigned_managed_identity
Title: "Add system-assigned managed identity to enable Guest Configuration assignments on VMs with a user-assigned identity"
Description: "This policy adds a system-assigned managed identity to virtual machines hosted in Azure that are supported by Guest Configuration and have at least one user-assigned identity but do not have a system-assigned managed identity. A system-assigned managed identity is a prerequisite for all Guest Configuration assignments and must be added to machines before using any Guest Configuration policy definitions."
Connector:
- azure
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |
    with gc_installed_vm as (
      select
        distinct a.vm_id,
        title
      from
        azure_compute_virtual_machine as a,
        jsonb_array_elements(extensions) as b
      where
        b ->> 'Publisher' = 'Microsoft.GuestConfiguration'
    )
    select
      a.vm_id as resource,
      a.kaytu_account_id as kaytu_account_id,
      a.kaytu_resource_id as kaytu_resource_id,
      case
        when b.vm_id is null then 'skip'
        when not string_to_array(a.identity ->> 'type' , ', ') @> array['UserAssigned'] then 'skip'
        when string_to_array(identity ->> 'type' , ', ') @> array['UserAssigned', 'SystemAssigned'] then 'ok'
        else 'alarm'
      end as status,
      case
        when b.vm_id is null then a.title || ' guest configuration extension not installed.'
        when not string_to_array(a.identity ->> 'type' , ', ') @> array['UserAssigned'] then a.title || ' does not have user assigned managed identity.'
        when string_to_array(identity ->> 'type' , ', ') @> array['UserAssigned', 'SystemAssigned'] then a.title || ' guest configuration extension installed with user and system assigned managed identity.'
        else a.title || ' guest configuration extension not installed with user and system assigned managed identity.'
      end as reason
      
      , a.resource_group as resource_group
      , sub.display_name as subscription
    from
      azure_compute_virtual_machine as a
      left join gc_installed_vm as b on a.vm_id = b.vm_id,
      azure_subscription as sub
    where
      sub.subscription_id = a.subscription_id;
  PrimaryTable: azure_compute_virtual_machine
  ListOfTables:
  - azure_compute_virtual_machine
  - azure_subscription
  Parameters: []
Severity: medium
Tags:
  nist_sp_800_53_rev_5:
  - "true"
  pci_dss_v321:
  - "true"
  service:
  - Azure/Compute
