id: azure_configure_emails_for_vulnerability_assessment_scan_reports_and_alerts
title: Configure Emails for Vulnerability Assessment Scan Reports and Alerts
description: Ensure that "Send scan reports to" setting is configured for SQL database servers.
integration_type:
  - azure_subscription
parameters: []
policy:
    language: sql
    primary_resource: azure_sql_server
    definition: |
        SELECT
          name AS resource,
          s.platform_resource_id,
          s.platform_integration_id,
          CASE
            WHEN vs -> 'properties' -> 'recurringScans' ->> 'emails' IS NULL THEN 'alarm'
            ELSE 'ok'
          END AS status,
          CASE
            WHEN vs -> 'properties' -> 'recurringScans' ->> 'emails' IS NULL THEN 'allows unrestricted ingress/inbound access for all the SQL databases hosted on the server.'
            ELSE 'does not allow unrestricted ingress/inbound access for all the SQL databases hosted on the server.'
          END AS reason,
          resource_group AS resource_group,
          sub.display_name AS subscription
        FROM
          azure_sql_server AS s
          LEFT JOIN azure_subscription AS sub ON s.subscription_id = sub.subscription_id,
          JSONB_ARRAY_ELEMENTS(server_vulnerability_assessment) AS vs
severity: medium
tags:
    platform_score_cloud_service_name:
      - Azure Managed SQL Service
    platform_score_use_case:
      - Exposed Endpoints
    score_service_name:
      - Azure Managed SQL Service
    score_tags:
      - Exposed Endpoints
