ID: aws_codebuild_project_with_user_controlled_buildspec
Title: CodeBuild projects should not use an user controlled buildspec
Description: This control checks if buildspec.yml is used from a trusted source which user cant interfere with.
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      arn as resource,
      kaytu_account_id as kaytu_account_id,
      kaytu_resource_id as kaytu_resource_id,
      case
        when split_part(source ->> 'Buildspec', '.', -1) = 'yml' then 'alarm'
        else 'ok'
      end as status,
      case
        when split_part(source ->> 'Buildspec', '.', -1) = 'yml' then title || ' uses a user controlled buildspec.'
        else title || ' does not uses a user controlled buildspec.'
      end as reason
      
      
    from
      aws_codebuild_project;
  PrimaryTable: ""
  ListOfTables: []
  Parameters: []
Connector:
- aws
Tags: {}
Severity: low
