id: azure_configure_audit_action_group_for_sql_server_auditing
title: Configure "AuditActionGroup" for SQL Server Auditing
description: Ensure that "AuditActionGroup" property is well configured at the Azure SQL database server level.
integration_type:
  - azure_subscription
parameters: []
policy:
    language: sql
    primary_resource: azure_sql_server
    definition: |
        SELECT
          name AS resource,
          s.platform_resource_id,
          s.platform_integration_id,
          CASE
            WHEN (
              SELECT ARRAY_AGG(g) 
              FROM jsonb_array_elements_text(ap -> 'properties' -> 'auditActionsAndGroups') AS g
            ) @> ARRAY['SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP', 'FAILED_DATABASE_AUTHENTICATION_GROUP', 'BATCH_COMPLETED_GROUP'] 
            THEN 'ok'
            ELSE 'alarm'
          END AS status,
          CASE
            WHEN (
              SELECT ARRAY_AGG(g) 
              FROM jsonb_array_elements_text(ap -> 'properties' -> 'auditActionsAndGroups') AS g
            ) @> ARRAY['SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP', 'FAILED_DATABASE_AUTHENTICATION_GROUP', 'BATCH_COMPLETED_GROUP'] 
            THEN 'AuditActionGroup property configuration for the selected Microsoft Azure SQL database server is compliant'
            ELSE 'AuditActionGroup property configuration for the selected Microsoft Azure SQL database server is not compliant'
          END AS reason,
          resource_group AS resource_group,
          sub.display_name AS subscription
        FROM
          azure_sql_server AS s
        LEFT JOIN
          azure_subscription AS sub 
        ON
          s.subscription_id = sub.subscription_id,
        jsonb_array_elements(server_audit_policy) AS ap
severity: medium
tags:
    platform_score_cloud_service_name:
      - Azure Managed SQL Service
    score_service_name:
      - Azure Managed SQL Service
