id: aws_api_gatewayv2_route_authorization_type_configured
title: API Gateway routes should specify an authorization type
description: This control checks if AWS API Gateway routes have an authorization type. The control fails if the API Gateway route does not specify an authorization type.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_api_gatewayv2_route
    definition: |
        SELECT
          'arn:' || partition || ':apigateway:' || region || '::/apis/' || api_id || '/routes/' || route_id AS resource,
          platform_integration_id AS platform_integration_id,
          platform_resource_id AS platform_resource_id,
          CASE
            WHEN authorization_type IS NULL THEN 'alarm'
            ELSE 'ok'
          END AS status,
          CASE
            WHEN authorization_type IS NULL THEN route_id || ' authorization type not configured.'
            ELSE route_id || ' authorization type ' || authorization_type || ' configured.'
          END AS reason,
          region,
          account_id
        FROM
          aws_api_gatewayv2_route;
severity: medium
tags:
    aws_foundational_security:
      - 'true'
    category:
      - Compliance
    foundational_security_category:
      - secure_access_management
    foundational_security_item_id:
      - apigateway_8
    plugin:
      - aws
    service:
      - AWS/APIGateway
