id: aws_config_configuration_recorder_no_failed_deliver_logs
title: Config configuration recorder should not fail to deliver logs
description: This control checks whether Config configuration recorder fails to deliver logs. This control is non-compliant if Config configuration recorder fails to deliver logs.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_config_configuration_recorder
    definition: |
        SELECT
          arn AS resource,
          platform_integration_id AS platform_integration_id,
          platform_resource_id AS platform_resource_id,
          CASE
            WHEN status ->> 'LastStatus' = 'FAILURE' THEN 'alarm'
            ELSE 'ok'
          END AS status,
          CASE
            WHEN status ->> 'LastStatus' = 'FAILURE' THEN title || ' has failed deliver logs.'
            ELSE title || ' does not have failed deliver logs.'
          END AS reason
        FROM
          aws_config_configuration_recorder;
severity: low
tags: {}
