id: aws_ec2_instance_no_iam_role_with_alter_critical_s3_permissions_configuration
title: EC2 instance IAM role should not allow to alter critical S3 permissions configuration
description: This control ensures that EC2 instance IAM role does not allow to alter critical s3 permissions configuration.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_ec2_instance
    definition: |
        WITH iam_roles AS (
          SELECT
            r.arn AS role_arn,
            i.arn AS instance_arn
          FROM
            aws_iam_role AS r,
            JSONB_ARRAY_ELEMENTS_TEXT(instance_profile_arns) AS p
            LEFT JOIN aws_ec2_instance AS i ON p = i.iam_instance_profile_arn
          WHERE
            i.arn IS NOT NULL
        ), iam_role_with_permission AS (
          SELECT
            arn
          FROM
            aws_iam_role,
            JSONB_ARRAY_ELEMENTS(assume_role_policy_std -> 'Statement') AS s,
            JSONB_ARRAY_ELEMENTS_TEXT(s -> 'Principal' -> 'Service') AS service,
            JSONB_ARRAY_ELEMENTS_TEXT(s -> 'Action') AS action
          WHERE
            arn IN (SELECT role_arn FROM iam_roles)
            AND s ->> 'Effect' = 'Allow'
            AND service = 'ec2.amazonaws.com'
            AND action IN (
              's3:PutObjectRetention', 's3:PutLifecycleConfiguration', 's3:PutBucketPolicy', 's3:PutBucketVersioning', '*:*'
            )
        )
        SELECT
          i.arn AS resource,
          i.platform_integration_id AS platform_integration_id,
          i.platform_resource_id AS platform_resource_id,
          CASE
            WHEN p.arn IS NULL THEN 'ok'
            ELSE 'alarm'
          END AS status,
          CASE
            WHEN p.arn IS NULL THEN title || ' has no IAM role with alter critical S3 permissions configuration.'
            ELSE title || ' has IAM role with alter critical S3 permissions configuration.'
          END AS reason
        FROM
          aws_ec2_instance AS i
          LEFT JOIN iam_roles AS r ON r.instance_arn = i.arn
          LEFT JOIN iam_role_with_permission AS p ON p.arn = r.role_arn;
severity: low
tags: {}
