id: aws_elastic_beanstalk_environment_managed_updates_enabled
title: Elastic Beanstalk environment should have managed updates enabled
description: This control checks whether managed platform updates in an AWS Elastic Beanstalk environment is enabled. The rule is COMPLIANT if the value for ManagedActionsEnabled is set to true. The rule is NON_COMPLIANT if the value for ManagedActionsEnabled is set to false, or if a parameter is provided and its value does not match the existing configurations.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_elastic_beanstalk_environment
    definition: |
        WITH beanstalk_environment_logs_enabled AS (
          SELECT
            DISTINCT e.arn
          FROM
            aws_elastic_beanstalk_environment AS e,
            jsonb_array_elements(e.configuration_settings) AS c,
            jsonb_array_elements(c -> 'OptionSettings') AS s
          WHERE
            s ->> 'OptionName' = 'ManagedActionsEnabled'
            AND s ->> 'Value' = 'true'
          GROUP BY
            e.arn
        )
        SELECT
          e.arn AS resource,
          e.platform_integration_id AS platform_integration_id,
          e.platform_resource_id AS platform_resource_id,
          CASE
            WHEN l.arn IS NOT NULL THEN 'ok'
            ELSE 'alarm'
          END AS status,
          CASE
            WHEN l.arn IS NOT NULL THEN title || ' managed actions Enabled.'
            ELSE title || ' managed actions disabled.'
          END AS reason
        FROM
          aws_elastic_beanstalk_environment AS e
        LEFT JOIN beanstalk_environment_logs_enabled AS l
        ON e.arn = l.arn;
severity: low
tags: {}
