id: aws_elb_application_network_lb_use_ssl_certificate
title: ELB application and network load balancers should only use SSL or HTTPS listeners
description: Ensure that Application Load Balancers and Network Load Balancers are configured to use certificates from AWS Certificate Manager (ACM). This rule is compliant if at least 1 load balancer is configured without a certificate from ACM.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: ''
    definition: |
        WITH listeners_without_certificate AS (
          SELECT
            load_balancer_arn,
            COUNT(*) AS count
          FROM
            aws_ec2_load_balancer_listener
          WHERE arn NOT IN (
            SELECT
              arn
            FROM
              aws_ec2_load_balancer_listener,
              jsonb_array_elements(certificates) AS c
            WHERE
              c ->> 'CertificateArn' LIKE 'arn:aws:acm%'
          )
          GROUP BY
            load_balancer_arn
        ),
        all_application_network_load_balancer AS (
          SELECT
            arn,
            account_id,
            region,
            title,
            platform_integration_id AS platform_integration_id,
            platform_resource_id AS platform_resource_id,
            'aws_ec2_application_load_balancer' AS platform_table_name,
            _ctx
          FROM
            aws_ec2_application_load_balancer
          UNION
          SELECT
            arn,
            account_id,
            region,
            title,
            platform_integration_id AS platform_integration_id,
            platform_resource_id AS platform_resource_id,
            'aws_ec2_network_load_balancer' AS platform_table_name,
            _ctx
          FROM
            aws_ec2_network_load_balancer
        )
        SELECT
          a.arn AS resource,
          a.platform_integration_id AS platform_integration_id,
          a.platform_resource_id AS platform_resource_id,
          a.platform_table_name AS platform_table_name,
          CASE
            WHEN b.load_balancer_arn IS NULL THEN 'ok'
            ELSE 'alarm'
          END AS status,
          CASE
            WHEN b.load_balancer_arn IS NULL THEN a.title || ' uses certificates provided by ACM.'
            ELSE a.title || ' has ' || b.count || ' listeners which do not use certificates provided by ACM.'
          END AS reason,
          a.region,
          a.account_id
        FROM
          all_application_network_load_balancer AS a
          LEFT JOIN listeners_without_certificate AS b ON a.arn = b.load_balancer_arn;
severity: low
tags:
    category:
      - Compliance
    cisa_cyber_essentials:
      - 'true'
    fedramp_moderate_rev_4:
      - 'true'
    ffiec:
      - 'true'
    gxp_21_cfr_part_11:
      - 'true'
    gxp_eu_annex_11:
      - 'true'
    hipaa_final_omnibus_security_rule_2013:
      - 'true'
    nist_800_53_rev_5:
      - 'true'
    nist_csf:
      - 'true'
    pci_dss_v321:
      - 'true'
    plugin:
      - aws
    rbi_cyber_security:
      - 'true'
    service:
      - AWS/ELB
