id: aws_vpc_security_group_restrict_ingress_tcp_udp_all
title: VPC security groups should restrict ingress TCP and UDP access from 0.0.0.0/0
description: Manage access to resources in the AWS Cloud by ensuring common ports are restricted on AWS Elastic Compute Cloud (AWS EC2) Security Groups.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_vpc_security_group
    definition: |
        WITH bad_rules AS (
          SELECT
            group_id,
            COUNT(*) AS num_bad_rules
          FROM
            aws_vpc_security_group_rule
          WHERE
            type = 'ingress'
            AND cidr_ipv4 = '0.0.0.0/0'
            AND (
              ip_protocol IN ('tcp', 'udp')
              OR (
                ip_protocol = '-1'
                AND from_port IS NULL
              )
            )
          GROUP BY
            group_id
        )
        SELECT
          arn AS resource,
          platform_integration_id AS platform_integration_id,
          platform_resource_id AS platform_resource_id,
          CASE
            WHEN bad_rules.group_id IS NULL THEN 'ok'
            ELSE 'alarm'
          END AS status,
          CASE
            WHEN bad_rules.group_id IS NULL THEN sg.group_id || ' does not allow ingress to TCP or UDP ports from 0.0.0.0/0.'
            ELSE sg.group_id || ' contains ' || bad_rules.num_bad_rules || ' rule(s) that allow ingress to TCP or UDP ports from 0.0.0.0/0.'
          END AS reason,
          region,
          account_id
        FROM
          aws_vpc_security_group AS sg
          LEFT JOIN bad_rules ON bad_rules.group_id = sg.group_id;
severity: high
tags:
    category:
      - Compliance
    cisa_cyber_essentials:
      - 'true'
    fedramp_low_rev_4:
      - 'true'
    fedramp_moderate_rev_4:
      - 'true'
    ffiec:
      - 'true'
    gxp_21_cfr_part_11:
      - 'true'
    hipaa_final_omnibus_security_rule_2013:
      - 'true'
    hipaa_security_rule_2003:
      - 'true'
    nist_800_53_rev_4:
      - 'true'
    nist_800_53_rev_5:
      - 'true'
    nist_800_171_rev_2:
      - 'true'
    nist_csf:
      - 'true'
    pci_dss_v321:
      - 'true'
    plugin:
      - aws
    rbi_cyber_security:
      - 'true'
    service:
      - AWS/VPC
    soc_2:
      - 'true'
