id: aws_autoscaling_ec2_launch_configuration_no_sensitive_data
title: EC2 auto scaling group launch configurations user data should not have any sensitive data
description: Ensure that sensitive information is not included in the user data of the launch configuration. It is recommended to utilize Secrets Manager as an alternative for securely managing sensitive data.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_ec2_launch_configuration
    definition: |
        SELECT
          launch_configuration_arn AS resource,
          platform_integration_id AS platform_integration_id,
          platform_resource_id AS platform_resource_id,
          CASE
            WHEN
              user_data LIKE ANY (ARRAY [ '%pass%', '%secret%', '%token%', '%key%' ])
              OR user_data ~ '(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]' THEN 'alarm'
            ELSE 'ok'
          END AS status,
          CASE
            WHEN
              user_data LIKE ANY (ARRAY [ '%pass%', '%secret%', '%token%', '%key%' ])
              OR user_data ~ '(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]' THEN title || ' has potential secret patterns in user data.'
            ELSE title || ' does not contain secret patterns in user data.'
          END AS reason
        FROM
          aws_ec2_launch_configuration;
severity: low
tags: {}
