id: aws_autoscaling_launch_config_public_ip_disabled
title: Auto Scaling launch config public IP should be disabled
description: Ensure that AWS EC2 Auto Scaling groups have public IP addresses enabled through Launch Configurations. This rule is non-compliant if the Launch Configuration for an Auto Scaling group has AssociatePublicIpAddress set to 'true'.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_ec2_launch_configuration
    definition: |
        SELECT
          launch_configuration_arn AS resource,
          platform_integration_id AS platform_integration_id,
          platform_resource_id AS platform_resource_id,
          CASE
            WHEN associate_public_ip_address THEN 'alarm'
            ELSE 'ok'
          END AS status,
          CASE
            WHEN associate_public_ip_address THEN title || ' public IP enabled.'
            ELSE title || ' public IP disabled.'
          END AS reason,
          region,
          account_id
        FROM
          aws_ec2_launch_configuration;
severity: high
tags:
    category:
      - Compliance
    cis_controls_v8_ig1:
      - 'true'
    cisa_cyber_essentials:
      - 'true'
    fedramp_low_rev_4:
      - 'true'
    fedramp_moderate_rev_4:
      - 'true'
    ffiec:
      - 'true'
    gxp_21_cfr_part_11:
      - 'true'
    hipaa_final_omnibus_security_rule_2013:
      - 'true'
    nist_800_53_rev_5:
      - 'true'
    nist_800_171_rev_2:
      - 'true'
    nist_csf:
      - 'true'
    pci_dss_v321:
      - 'true'
    plugin:
      - aws
    rbi_cyber_security:
      - 'true'
    service:
      - AWS/AutoScaling
