id: aws_elb_application_classic_network_lb_prohibit_public_access
title: ELB load balancers should prohibit public access
description: An internet facing load balancer has a publicly resolvable DNS name, so it can route requests from clients over the internet to the EC2 instances that are registered with the load balancer.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_ec2_application_load_balancer
    definition: |
        WITH all_lb_details AS (
          SELECT
            arn,
            scheme,
            title,
            region,
            account_id,
            tags,
            _ctx,
            platform_integration_id,
            platform_resource_id
          FROM
            aws_ec2_application_load_balancer
          UNION
          SELECT
            arn,
            scheme,
            title,
            region,
            account_id,
            tags,
            _ctx,
            platform_integration_id,
            platform_resource_id
          FROM
            aws_ec2_network_load_balancer
          UNION
          SELECT
            arn,
            scheme,
            title,
            region,
            account_id,
            tags,
            _ctx,
            platform_integration_id,
            platform_resource_id
          FROM
            aws_ec2_classic_load_balancer
        )
        SELECT
          arn AS resource,
          platform_integration_id AS platform_integration_id,
          platform_resource_id AS platform_resource_id,
          CASE
            WHEN scheme = 'internet-facing' THEN 'alarm'
            ELSE 'ok'
          END AS status,
          CASE
            WHEN scheme = 'internet-facing' THEN title || ' publicly accessible.'
            ELSE title || ' not publicly accessible.'
          END AS reason
        FROM
          all_lb_details;
severity: low
tags: {}
