id: aws_vpc_security_group_restrict_ingress_rdp_all
title: Ensure no security groups allow ingress from 0.0.0.0/0 to port 3389
description: Security groups provide stateful filtering of ingress/egress network traffic to AWS resources. It is recommended that no security group allows unrestricted ingress access to port 3389.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_vpc_security_group
    definition: |
        WITH ingress_rdp_rules AS (
          SELECT
            group_id,
            COUNT(*) AS num_rdp_rules
          FROM
            aws_vpc_security_group_rule
          WHERE
            type = 'ingress'
            AND cidr_ipv4 = '0.0.0.0/0'
            AND (
              (ip_protocol = '-1' AND from_port IS NULL)
              OR (from_port >= 3389 AND to_port <= 3389)
            )
          GROUP BY
            group_id
        )
        SELECT
          arn AS resource,
          platform_integration_id AS platform_integration_id,
          platform_resource_id AS platform_resource_id,
          CASE
            WHEN ingress_rdp_rules.group_id IS NULL THEN 'ok'
            ELSE 'alarm'
          END AS status,
          CASE
            WHEN ingress_rdp_rules.group_id IS NULL THEN CONCAT(sg.group_id, ' ingress restricted for RDP from 0.0.0.0/0.')
            ELSE CONCAT(sg.group_id, ' contains ', ingress_rdp_rules.num_rdp_rules, ' ingress rule(s) allowing RDP from 0.0.0.0/0.')
          END AS reason,
          sg.region,
          sg.account_id
        FROM
          aws_vpc_security_group AS sg
        LEFT JOIN
          ingress_rdp_rules ON ingress_rdp_rules.group_id = sg.group_id
severity: high
tags:
    category:
      - Compliance
    cis:
      - 'true'
    cis_item_id:
      - '4.2'
    cis_level:
      - '1'
    cis_section_id:
      - '4'
    cis_type:
      - scored
    cis_version:
      - v1.2.0
    plugin:
      - aws
    service:
      - AWS/VPC
