id: aws_elastic_beanstalk_environment_logs_to_cloudwatch
title: Elastic Beanstalk should stream logs to CloudWatch
description: This control checks whether an Elastic Beanstalk environment is configured to send logs to CloudWatch Logs. The control fails if an Elastic Beanstalk environment isn't configured to send logs to CloudWatch Logs. Optionally, you can provide a custom value for the RetentionInDays parameter if you want the control to pass only if logs are retained for the specified number of days before expiration.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_elastic_beanstalk_environment
    definition: |
        WITH beanstalk_environment_logs_enabled AS (
          SELECT
            DISTINCT e.arn
          FROM
            aws_elastic_beanstalk_environment AS e,
            jsonb_array_elements(e.configuration_settings) AS c,
            jsonb_array_elements(c -> 'OptionSettings') AS s
          WHERE
            s ->> 'OptionName' = 'StreamLogs'
            AND s ->> 'Value' = 'true'
          GROUP BY
            arn
        )
        SELECT
          e.arn AS resource,
          e.platform_integration_id AS platform_integration_id,
          e.platform_resource_id AS platform_resource_id,
          CASE
            WHEN l.arn IS NOT NULL THEN 'ok'
            ELSE 'alarm'
          END AS status,
          CASE
            WHEN l.arn IS NOT NULL THEN title || ' send logs to AWS CloudWatch.'
            ELSE title || ' does not send logs to AWS CloudWatch.'
          END AS reason
        FROM
          aws_elastic_beanstalk_environment AS e
          LEFT JOIN beanstalk_environment_logs_enabled AS l ON e.arn = l.arn;
severity: low
tags: {}
