id: aws_glue_data_catalog_encryption_settings_password_encryption_enabled
title: Glue data catalog connection password encryption should be enabled
description: Ensure Glue data catalog connection password encryption is enabled to protect sensitive information at rest.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_glue_data_catalog_encryption_settings
    definition: |
        SELECT
          'arn:' || partition || '::' || region || ':' || account_id AS resource,
          platform_integration_id AS platform_integration_id,
          platform_resource_id AS platform_resource_id,
          CASE
            WHEN connection_password_encryption IS NOT NULL 
              AND connection_password_encryption ->> 'ReturnConnectionPasswordEncrypted' != 'false' THEN 'ok'
            ELSE 'alarm'
          END AS status,
          CASE
            WHEN connection_password_encryption IS NOT NULL 
              AND connection_password_encryption ->> 'ReturnConnectionPasswordEncrypted' != 'false' THEN 'Glue data catalog connection password encryption enabled in ' || region || '.'
            ELSE 'Glue data catalog connection password encryption disabled in ' || region || '.'
          END AS reason
        FROM
          aws_glue_data_catalog_encryption_settings;
severity: low
tags: {}
