id: aws_api_gateway_method_authorization_type_configured
title: API Gateway methods authorizer should be configured
description: This control checks whether API Gateway method has an authorizer configured. This rule is non-compliant if API Gateway method has no authorizers configured.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_api_gateway_method
    definition: |
        SELECT
          resource_id AS resource,
          platform_integration_id AS platform_integration_id,
          platform_resource_id AS platform_resource_id,
          CASE
            WHEN authorization_type = 'NONE' THEN 'alarm'
            ELSE 'ok'
          END AS status,
          CASE
            WHEN authorization_type = 'NONE' THEN title || ' authorization type not configured.'
            ELSE title || ' authorization type ' || authorization_type || ' configured.'
          END AS reason
        FROM
          aws_api_gateway_method;
severity: low
tags: {}
