id: aws_glue_data_catalog_encryption_settings_metadata_encryption_enabled
title: Glue data catalog metadata encryption should be enabled
description: Ensure Glue data catalog metadata encryption is enabled to protect sensitive information at rest.
integration_type:
  - aws_cloud_account
parameters: []
policy:
    language: sql
    primary_resource: aws_glue_data_catalog_encryption_settings
    definition: |
        SELECT
          'arn:' || partition || '::' || region || ':' || account_id AS resource,
          platform_integration_id AS platform_integration_id,
          platform_resource_id AS platform_resource_id,
          CASE
            WHEN encryption_at_rest IS NOT NULL 
              AND encryption_at_rest ->> 'CatalogEncryptionMode' != 'DISABLED' THEN 'ok'
            ELSE 'alarm'
          END AS status,
          CASE
            WHEN encryption_at_rest IS NOT NULL 
              AND encryption_at_rest ->> 'CatalogEncryptionMode' != 'DISABLED' THEN 'Glue data catalog metadata encryption is enabled in ' || region || '.'
            ELSE 'Glue data catalog metadata encryption is disabled in ' || region || '.'
          END AS reason
        FROM
          aws_glue_data_catalog_encryption_settings;
severity: low
tags: {}
